server:
  port: 9090
  servlet:
    context-path: "/api"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digikala
    username: postgres
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  main:
    allow-circular-references: true
